### ISSUE TITLE
Mark broken packages

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/msprime-feedstock#24]
Hi @conda-forge/core,

Please move my package from ``main`` to ``broken`` on the conda-forge channel on anaconda.org
because the solver is minimising the features installed (i.e., no openblas), resulting in broken packages being preferred over more recent working ones.

It would be very helpful if you could move all of the builds msprime-0.6.2-X before the most recent build 3 to broken, please.

See #20 for more background.

**Comment by ocefpaf** [comment]
Done! Can you please check if I got ir right?

https://anaconda.org/conda-forge/msprime/files?version=0.6.2

**Comment by jeromekelleher** [comment]
Perfect! Thank you @ocefpaf!
