### ISSUE TITLE
Create rc label and remove pre-release package from main

### ISSUE THREAD

**Issue by jeromekelleher** [conda-forge/msprime-feedstock#47]
Hi @conda-forge/core! 

I tried to create a pre-release package for this feedstock following the advice [here](https://conda-forge.org/docs/maintainer/knowledge_base.html#creating-a-pre-release-build). I created the [rc branch](https://github.com/conda-forge/msprime-feedstock/tree/rc) and updated the recipe (and added ``recipe/conda_build_config.yaml`` file) in PRs #44 and #45. (Unfortunately I got the name of the ``conda_build_config`` yaml file wrong in #44 and had to correct it in #45)

The packages build successfully, so I merged the PRs. However, the ``msprime_rc`` label I was expecting is not present on [anaconda.org](https://anaconda.org/conda-forge/msprime), and the 1.0.0a6 packages are now in the ``main`` label. I've tried out some installs, and sometimes conda installs the stable 0.7.4 and other times the pre-release 1.0.0a6. 

This is unfortunate because I hadn't intended for users to install the pre-release yet, and was making the conda package to unblock some downstream development, depending on the new version, and we need to have conda packages for CI.

It would be very, very helpful if you could make the ``msprime_rc`` label, and move all the ``*1.0.0*`` packages to this label. If that's not possible, then it would be very helpful if we could move the ``*1.0.0*`` packages to ``broken`` so that users aren't unknowingly installing pre-releases.

Any pointers on what I did wrong would be much appreciated, if it's obvious.

Thanks for all the hard work, and apologies for adding more to your pile!

**Comment by ocefpaf** [comment]
I moved them to the rc label. See https://anaconda.org/conda-forge/msprime/files?version=1.0.0a6&channel=msprime_rc

PS: moving to broken is also an option and that one would not require a member of core. We can do those now with a PR to adim requests. See https://conda-forge.org/docs/maintainer/updating_pkgs.html?#removing-broken-packages for more info.

**Comment by jeromekelleher** [comment]
Thank you so much @ocefpaf, you are a life-saver! :heart:

**Comment by jeromekelleher** [comment]
Thanks for the info too, great to know we can move to broken ourselves too.
