### ISSUE TITLE
HDF5 linkage issues

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/msprime-feedstock#6]
Copying from @alimahmoudi29's [comment]( https://github.com/conda-forge/h5py-feedstock/issues/25#issuecomment-368387143 ).

> **I received the following error:** 
> ```
> Traceback (most recent call last):
>   File "/anaconda3/bin/mspms", line 4, in <module>
>     import msprime.cli
>   File "/anaconda3/lib/python3.6/site-packages/msprime/__init__.py", line 26, in <module>
>     from _msprime import FORWARD  # NOQA
> ImportError: dlopen(/anaconda3/lib/python3.6/site-packages/_msprime.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libhdf5.10.dylib
>   Referenced from: /anaconda3/lib/python3.6/site-packages/_msprime.cpython-36m-darwin.so
>   Reason: image not found
> ```
> 
> **I fixed the issue by 
> mv libhdf5.101.dylib libhdf5.10.dylib**  in directory **/usr/local/lib** .

**Comment by jakirkham** [comment]
Would add that it appears that [`hdf5` is not pinned]( https://github.com/conda-forge/msprime-feedstock/blob/2c1567efc8306abfa66be64ccec83a02291d259e/recipe/meta.yaml#L37 ) in this package as it should be. The package should be rebuilt with [`hdf5` correctly pinned]( https://github.com/conda-forge/conda-forge.github.io/blob/c26825a385801667d8f2704c837b32aced8fdb4f/scripts/pin_the_slow_way.py#L83 ). We will need to pull the packages that were not pinned once this is done.

**Comment by jeromekelleher** [comment]
Ugh, sorry for this @jakirkham, my bad. I was trying to muddle my way through without bothering you and the other maintainers, but it appears this has done more harm than good...

I've pinned HDF5 following the examples in other feedstocks, so hopefully it's OK now. Let me know if there's anything I can do to help clear up the mess.

**Comment by jakirkham** [comment]
No worries. If you see this issue other places, please us know.

Looks better. Have pulled the packages that didn't have `hdf5` pinned, which should avoid users getting these accidentally. Please double check that we got them all and got the right ones.

**Comment by jeromekelleher** [comment]
Great, thanks. Just checked the packages on anaconda cloud, and they look right to me.

**Comment by alimahmoudi29** [comment]
It works now, thanks
